# configs/train_config.yaml

data:
  path: "data/CelebA-HQ/images_512"
  image_size: 512
  normalize: true
  captions: "data/CelebA-HQ-Captions.csv"

model:
  type: dit
  latent_dim: 4
  img_size: 64
  hidden_size: 768 # hidden_size = num_heads × attention_head_dim
  depth: 12
  num_heads: 12
  attn_head_dim: 64
  patch_size: 1

training:
  validation_split: 0
  epochs: 5
  batch_size: 2
  lr: 1e-4
  grad_accum_steps: 2
  use_ema: true
  ema_beta: 0.995
  step_start_ema: 2000
  num_workers: 4

scheduler:
  type: linear
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
