# configs/train_config.yaml

data:
  path: "data/CelebA-HQ/images_512"  # Local Images Path
  parquet_path: "/dbfs/mnt/ds-space/Hitesh/Datasets/CelebA-HQ/parquet_files/CelebA-HQ.parquet"  # Parquet Dataset Path:  /dbfs/mnt/ds-space/Hitesh/Datasets/CelebA-HQ/parquet_files/CelebA-HQ.parquet
  image_size: 512            
  normalize: True
  captions: "data/CelebA-HQ-Captions.csv" #  Latter 

checkpoint:
  path: "/dbfs/mnt/ds-space/Hitesh/Checkpoints/" # Checkpoint Path: /dbfs/mnt/ds-space/Hitesh/Checkpoints/
  ckpt_name: "dit_diffusion_ckpt_512.pth"
  ema_ckpt_name: "dit_diffusion_ema_ckpt_512.pth"

output_dir:
  train: "output/train" # Training Samples Output Directory
  test: "output/test" # Inference Samples Output Directory

training:
  batch_size: 4
  validation_split: 0
  epochs: 100
  warmup_epochs: 10
  lr: 1e-4
  grad_accum_steps: 2
  use_ema: true
  ema_beta: 0.995
  step_start_ema: 2000
  num_workers: 4

sampling:
  dir: "output/samples"
  num_samples: 25                    # Keep same for consistency
  steps: 50             # Adjusted for faster inference
  # guidance_scale: 7.5                 # Adjusted for better quality

model:
  type: dit
  latent_dim: 4
  img_size: 64
  hidden_size: 768 # hidden_size = num_heads × attention_head_dim
  depth: 12
  num_heads: 12
  attn_head_dim: 64
  patch_size: 1


scheduler:
  type: squaredcos_cap_v2
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

logs: "logs"